export const STATES = [
  {
    'hc-a2': 'AL',
    name: 'Alabama',
    region: 'South',
    x: 6,
    y: 7,
    value: 0,
  },
  {
    'hc-a2': 'AK',
    name: 'Alaska',
    region: 'West',
    x: 0,
    y: 0,
    value: 0,
  },
  {
    'hc-a2': 'AZ',
    name: 'Arizona',
    region: 'West',
    x: 5,
    y: 3,
    value: 0,
  },
  {
    'hc-a2': 'AR',
    name: 'Arkansas',
    region: 'South',
    x: 5,
    y: 6,
    value: 0,
  },
  {
    'hc-a2': 'CA',
    name: 'California',
    region: 'West',
    x: 5,
    y: 2,
    value: 0,
  },
  {
    'hc-a2': 'CO',
    name: 'Colorado',
    region: 'West',
    x: 4,
    y: 3,
    value: 0,
  },
  {
    'hc-a2': 'CT',
    name: 'Connecticut',
    region: 'Northeast',
    x: 3,
    y: 11,
    value: 0,
  },
  {
    'hc-a2': 'DE',
    name: 'Delaware',
    region: 'South',
    x: 4,
    y: 9,
    value: 0,
  },
  {
    'hc-a2': 'DC',
    name: 'District of Columbia',
    region: 'South',
    x: 4,
    y: 10,
    value: 0,
  },
  {
    'hc-a2': 'FL',
    name: 'Florida',
    region: 'South',
    x: 8,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'GA',
    name: 'Georgia',
    region: 'South',
    x: 7,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'HI',
    name: 'Hawaii',
    region: 'West',
    x: 8,
    y: 0,
    value: 0,
  },
  {
    'hc-a2': 'ID',
    name: 'Idaho',
    region: 'West',
    x: 3,
    y: 2,
    value: 0,
  },
  {
    'hc-a2': 'IL',
    name: 'Illinois',
    region: 'Midwest',
    x: 3,
    y: 6,
    value: 0,
  },
  {
    'hc-a2': 'IN',
    name: 'Indiana',
    region: 'Midwest',
    x: 3,
    y: 7,
    value: 0,
  },
  {
    'hc-a2': 'IA',
    name: 'Iowa',
    region: 'Midwest',
    x: 3,
    y: 5,
    value: 0,
  },
  {
    'hc-a2': 'KS',
    name: 'Kansas',
    region: 'Midwest',
    x: 5,
    y: 5,
    value: 0,
  },
  {
    'hc-a2': 'KY',
    name: 'Kentucky',
    region: 'South',
    x: 4,
    y: 6,
    value: 0,
  },
  {
    'hc-a2': 'LA',
    name: 'Louisiana',
    region: 'South',
    x: 6,
    y: 5,
    value: 0,
  },
  {
    'hc-a2': 'ME',
    name: 'Maine',
    region: 'Northeast',
    x: 0,
    y: 11,
    value: 0,
  },
  {
    'hc-a2': 'MD',
    name: 'Maryland',
    region: 'South',
    x: 4,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'MA',
    name: 'Massachusetts',
    region: 'Northeast',
    x: 2,
    y: 10,
    value: 0,
  },
  {
    'hc-a2': 'MI',
    name: 'Michigan',
    region: 'Midwest',
    x: 2,
    y: 7,
    value: 0,
  },
  {
    'hc-a2': 'MN',
    name: 'Minnesota',
    region: 'Midwest',
    x: 2,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'MS',
    name: 'Mississippi',
    region: 'South',
    x: 6,
    y: 6,
    value: 0,
  },
  {
    'hc-a2': 'MO',
    name: 'Missouri',
    region: 'Midwest',
    x: 4,
    y: 5,
    value: 0,
  },
  {
    'hc-a2': 'MT',
    name: 'Montana',
    region: 'West',
    x: 2,
    y: 2,
    value: 0,
  },
  {
    'hc-a2': 'NE',
    name: 'Nebraska',
    region: 'Midwest',
    x: 4,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'NV',
    name: 'Nevada',
    region: 'West',
    x: 4,
    y: 2,
    value: 0,
  },
  {
    'hc-a2': 'NH',
    name: 'New Hampshire',
    region: 'Northeast',
    x: 1,
    y: 11,
    value: 0,
  },
  {
    'hc-a2': 'NJ',
    name: 'New Jersey',
    region: 'Northeast',
    x: 3,
    y: 10,
    value: 0,
  },
  {
    'hc-a2': 'NM',
    name: 'New Mexico',
    region: 'West',
    x: 6,
    y: 3,
    value: 0,
  },
  {
    'hc-a2': 'NY',
    name: 'New York',
    region: 'Northeast',
    x: 2,
    y: 9,
    value: 0,
  },
  {
    'hc-a2': 'NC',
    name: 'North Carolina',
    region: 'South',
    x: 5,
    y: 9,
    value: 0,
  },
  {
    'hc-a2': 'ND',
    name: 'North Dakota',
    region: 'Midwest',
    x: 2,
    y: 3,
    value: 0,
  },
  {
    'hc-a2': 'OH',
    name: 'Ohio',
    region: 'Midwest',
    x: 3,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'OK',
    name: 'Oklahoma',
    region: 'South',
    x: 6,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'OR',
    name: 'Oregon',
    region: 'West',
    x: 4,
    y: 1,
    value: 0,
  },
  {
    'hc-a2': 'PA',
    name: 'Pennsylvania',
    region: 'Northeast',
    x: 3,
    y: 9,
    value: 0,
  },
  {
    'hc-a2': 'RI',
    name: 'Rhode Island',
    region: 'Northeast',
    x: 2,
    y: 11,
    value: 0,
  },
  {
    'hc-a2': 'SC',
    name: 'South Carolina',
    region: 'South',
    x: 6,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'SD',
    name: 'South Dakota',
    region: 'Midwest',
    x: 3,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'TN',
    name: 'Tennessee',
    region: 'South',
    x: 5,
    y: 7,
    value: 0,
  },
  {
    'hc-a2': 'TX',
    name: 'Texas',
    region: 'South',
    x: 7,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'UT',
    name: 'Utah',
    region: 'West',
    x: 5,
    y: 4,
    value: 0,
  },
  {
    'hc-a2': 'VT',
    name: 'Vermont',
    region: 'Northeast',
    x: 1,
    y: 10,
    value: 0,
  },
  {
    'hc-a2': 'VA',
    name: 'Virginia',
    region: 'South',
    x: 5,
    y: 8,
    value: 0,
  },
  {
    'hc-a2': 'WA',
    name: 'Washington',
    region: 'West',
    x: 2,
    y: 1,
    value: 0,
  },
  {
    'hc-a2': 'WV',
    name: 'West Virginia',
    region: 'South',
    x: 4,
    y: 7,
    value: 0,
  },
  {
    'hc-a2': 'WI',
    name: 'Wisconsin',
    region: 'Midwest',
    x: 2,
    y: 5,
    value: 0,
  },
  {
    'hc-a2': 'WY',
    name: 'Wyoming',
    region: 'West',
    x: 3,
    y: 3,
    value: 0,
  },
];

export const LANE_DETAILS = {
  laneId: 'FT1201202121-1',
  equipmentId: 27,
  equipmentValue: "53' PLATE TR",
  commodityId: null,
  weight: 150,
  cargoValue: 1500,
  originCity: 'Miami',
  originState: 'FL',
  originZipCode: '33101',
  destinationCity: 'New York',
  destinationState: 'NY',
  destinationZipCode: '10279',
  stops: 0,
  totalMiles: 1295,
  total: 0,
  awarded: null,
  temperatureValue: '',
  packageTypeId: 33,
  packageTypeValue: 'Bale',
  piecesValue: null,
  quoteId: 0,
  hazmat: null,
  hazmatClass: null,
  hazmatName: null,
  hazmatUN: null,
  commodityValue: 'ADHESIVES',
  routingTotalMiles: 1295,
  laneAccessorials: [],
  laneChargesViewModel: {
    rateTypeId: 306,
    rateType: 'Per Mile',
    tripChargesRecommended: false,
    cost: null,
    typeId: null,
    type: null,
    rate: 0,
    sell: 0,
    total: 0,
    profit: 0,
    stops: 0,
    stopRate: null,
    stopTotal: 0,
    accessorialQuantity: 0,
    accessorialTotal: 0,
    surchargesTypeId: null,
    surchargesType: null,
    surChargeRate: null,
    surChargeTotal: 0,
    roundRate: false,
    subTotal: 0,
    finalTotal: 0,
    laneId: 5076,
    createdByID: null,
    updatedByID: null,
    deletedByID: null,
    id: 5054,
    createdDate: '0001-01-01T00:00:00',
    updatedDate: null,
    deletedDate: null,
  },
  routing: {
    futload: 0,
    laneId: 5076,
    originType: 'Shipper',
    originCity: 'Miami',
    originState: 'FL',
    originZipcode: '33101',
    originCounty: 'Miami-Dade',
    originCountry: 'United States',
    originMiles: 0,
    destinationType: 'Consignee',
    destinationCity: 'New York',
    destinationState: 'NY',
    destinationZipcode: '10279',
    destinationCounty: 'New York',
    destinationCountry: 'United States',
    destinationMiles: 1295,
    originLat: '25.779304',
    originLon: '-80.198521',
    destinationLat: '40.712674',
    destinationLon: '-74.008752',
    createdByID: '86894a76-fc27-415f-a740-5b24a7390394',
    updatedByID: '86894a76-fc27-415f-a740-5b24a7390394',
    deletedByID: null,
    id: 5054,
    createdDate: '2021-12-01T07:43:28.4837921',
    updatedDate: '2021-12-01T12:20:02.2333705',
    deletedDate: null,
  },
  routingStops: [],
  preDefinedCommentId: null,
  preDefinedCommentValue: null,
  comment: '',
  originRadius: null,
  destinationRadius: null,
  ltRatio: 1,
  statusId: 323,
  status: 'Lost',
  commentTemplateId: null,
  isNoneSelected: true,
  commentTemplateName: '',
  id: 5076,
  createdDate: '0001-01-01T00:00:00',
  updatedDate: null,
  deletedDate: null,
};

export const PATH = [
  {
    key: 'ND',
    title: 'O',
    src: 'origin',
    path: 'Origin',
    shipType: 'Shipper',
    city: 'Fargo',
    distance: 0,
  },
  {
    key: 'WY',
    title: 'S1',
    src: 'stop',
    path: 'Stop 1',
    shipType: 'Consignee',
    city: '	Casper',
    distance: 719,
  },
  {
    key: 'CO',
    title: 'S2',
    src: 'stop',
    path: 'Stop 2',
    shipType: 'Consignee',
    city: 'Denver',
    distance: '275',
  },
  {
    key: 'UT',
    title: 'S3',
    src: 'stop',
    path: 'Stop 3',
    shipType: 'Consignee',
    city: 'Provo',
    distance: '481',
  },
  {
    key: 'OK',
    title: 'S4',
    src: 'stop',
    path: 'Stop 4',
    shipType: 'Consignee',
    city: 'Tulsa',
    distance: '275',
  },
  {
    key: 'LA',
    title: 'S5',
    src: 'stop',
    path: 'Stop 5',
    shipType: 'Consignee',
    city: 'Houma',
    distance: 1172,
  },
  {
    key: 'MS',
    title: 'S6',
    src: 'dest',
    path: 'Destination',
    shipType: 'Consignee',
    city: 'Gulfport',
    distance: 132,
  },
  // {
  //   key: 'AL',
  //   title: 'S7',
  //   src: 'stop',
  //   path: 'Stop 7',
  //   shipType: 'Consignee',
  //   city: 'Dothan',
  //   distance: 270,
  // },
  // {
  //   key: 'GA',
  //   title: 'S8',
  //   src: 'stop',
  //   path: 'Stop 8',
  //   shipType: 'Consignee',
  //   city: 'Atlanta',
  //   distance: 491,
  // },
  // {
  //   key: 'FL',
  //   title: 'D',
  //   src: 'dest',
  //   path: 'Destination',
  //   shipType: 'Consignee',
  //   city: 'Miami',
  //   distance: 234,
  // },
];
